// Code generated by "stringer -type VType"; DO NOT EDIT.

package goudp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[I64-1]
	_ = x[U64-2]
	_ = x[F64-3]
	_ = x[Str-4]
	_ = x[Bool-5]
	_ = x[Array-6]
	_ = x[Object-7]
	_ = x[UDT-8]
}

const _VType_name = "UndefinedI64U64F64StrBoolArrayObjectUDT"

var _VType_index = [...]uint8{0, 9, 12, 15, 18, 21, 25, 30, 36, 39}

func (i VType) String() string {
	if i < 0 || i >= VType(len(_VType_index)-1) {
		return "VType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VType_name[_VType_index[i]:_VType_index[i+1]]
}
